[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 20.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.9
padding = { x = 12, y = 10 }
dynamic_padding = true
option_as_alt = "OnlyLeft"
