[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Iosevka Nerd Font"

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 2 }
dynamic_padding = true
option_as_alt = "OnlyLeft"
