format = """$username\
$directory\
$git_branch\
$git_state\
$git_status\n\
$character"""

[directory]
style = "white"

[character]
success_symbol = "[\\$](bright-black)"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[\\$](bright-black)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[zig]
symbol = '  '
